# Generated by Django 2.2.6 on 2020-02-24 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Department',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default=2, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
