# Generated by Django 2.2.6 on 2020-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200225_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Return',
            field=models.BooleanField(default=False),
        ),
    ]
