# Generated by Django 2.2.6 on 2020-02-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200228_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Received',
            new_name='Deliverd',
        ),
    ]
