# Generated by Django 2.2.6 on 2020-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200228_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=1000)),
                ('Rates', models.IntegerField()),
                ('Book_Recieved', models.CharField(max_length=10)),
                ('SameBook', models.CharField(max_length=10)),
            ],
        ),
    ]
