# Generated by Django 2.2.6 on 2020-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Message',
            field=models.TextField(),
        ),
    ]
